---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zayn.
--- DateTime: 2024/7/22 下午5:36
---

local voucherId = argv[1]
local userId = argv[2]
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

-- 判断库存是否足够
if tonumber(redis.call('get', stockKey)) <= 0 then
    -- 库存不足
    return 1
end

-- 判断用户是否已经抢购过
if redis.call('sismember', orderKey, userId) == 1 then
    -- 重复抢购
    return 2
end

-- 减库存
redis.call('incrby', stockKey, -1)

-- 记录下单用户
redis.call('sadd', orderKey, userId)

return 0